root - ERROR - Error while using ARMA on ship_pt: ZTRD, prod_hierarchy: TEST, part_number: CORONA
root - ERROR - Traceback (most recent call last):
  File "/home/aditya_user/time-forecast-app/processing/process.py", line 60, in run
    rmse, mape, pred = algo_obj.get_predictions_rmse_mape(algo_name)
  File "/home/aditya_user/time-forecast-app/processing/algorithms.py", line 132, in get_predictions_rmse_mape
    model_fit = model.fit(disp=0)
  File "/home/aditya_user/time-forecast-app/venv/lib/python3.7/site-packages/statsmodels/tsa/arima_model.py", line 986, in fit
    start_ar_lags)
  File "/home/aditya_user/time-forecast-app/venv/lib/python3.7/site-packages/statsmodels/tsa/arima_model.py", line 577, in _fit_start_params
    start_params = self._fit_start_params_hr(order, start_ar_lags)
  File "/home/aditya_user/time-forecast-app/venv/lib/python3.7/site-packages/statsmodels/tsa/arima_model.py", line 555, in _fit_start_params_hr
    raise ValueError("The computed initial AR coefficients are not "
ValueError: The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.

